environment:
    matrix:
        - PYTHON: "C:\\Python37-x64"
          WHEEL_PLATFORM: win_amd64
        - PYTHON: "C:\\Python38-x64"
          WHEEL_PLATFORM: win_amd64

install:
    - set "PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%"
    - python -m pip install wheel poetry

build: off

test_script:
    - python -m poetry install -v
    - python -m poetry pytest --full-trace --showlocals
