# Docs:
# https://github.com/actions/setup-python
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO: Add MacOS (macos-latest)
        os: [ubuntu-latest]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Ubuntu Packages
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get update && sudo apt-get install --yes libgirepository1.0-dev libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++ python3-dev

      - name: MacOS Packages
        if: ${{ matrix.os == 'macos-latest' }}
        run: brew install cairo gobject-introspection

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry coveralls

      - name: Poetry install
        run: poetry sync --with dev --verbose

      - name: mypy
        run: make mypy

      - name: test
        run: make test-coverage

      # Only need to upload coverage data once.
      - name: upload coverage to codecov.io
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12' }}
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          verbose: true
